apiVersion: apps/v1
kind: Deployment
metadata:
  name: archiverse
  namespace: archiverse
spec:
  selector:
    matchLabels:
      app: archiverse
  template:
    metadata:
      labels:
        app: archiverse
    spec:
      imagePullSecrets:
      - name: acr-secret
      containers:
      - name: archiverse
        image: archiverseacr.azurecr.io/archiverse:latest # {"$imagepolicy": "flux-system:archiverse"}
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        env:
        - name: NODE_ENV
          value: production
        - name: APP_BASE_URL
          valueFrom:
            secretKeyRef:
              name: archiverse-secrets
              key: APP-BASE-URL
        - name: NEXT_PUBLIC_AUTH0_DOMAIN
          valueFrom:
            secretKeyRef:
              name: archiverse-secrets
              key: NEXT-PUBLIC-AUTH0-DOMAIN
        - name: AUTH0_MANAGEMENT_API_DOMAIN
          valueFrom:
            secretKeyRef:
              name: archiverse-secrets
              key: AUTH0-MANAGEMENT-API-DOMAIN
        - name: SESSION_ENCRYPTION_SECRET
          valueFrom:
            secretKeyRef:
              name: archiverse-secrets
              key: SESSION-ENCRYPTION-SECRET
        - name: AUTH0_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: archiverse-secrets
              key: AUTH0-CLIENT-ID
        - name: AUTH0_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: archiverse-secrets
              key: AUTH0-CLIENT-SECRET
        - name: AUTH0_MANAGEMENT_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: archiverse-secrets
              key: AUTH0-MANAGEMENT-CLIENT-ID
        - name: AUTH0_MANAGEMENT_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: archiverse-secrets
              key: AUTH0-MANAGEMENT-CLIENT-SECRET
        - name: AUTH0_ADMIN_ROLE_ID
          valueFrom:
            secretKeyRef:
              name: archiverse-secrets
              key: AUTH0-ADMIN-ROLE-ID
        - name: AUTH0_MEMBER_ROLE_ID
          valueFrom:
            secretKeyRef:
              name: archiverse-secrets
              key: AUTH0-MEMBER-ROLE-ID
        - name: DEFAULT_CONNECTION_ID
          valueFrom:
            secretKeyRef:
              name: archiverse-secrets
              key: DEFAULT-CONNECTION-ID
        - name: CUSTOM_CLAIMS_NAMESPACE
          valueFrom:
            secretKeyRef:
              name: archiverse-secrets
              key: CUSTOM-CLAIMS-NAMESPACE
        volumeMounts:
        - name: secrets-store
          mountPath: "/mnt/secrets-store"
          readOnly: true
      volumes:
      - name: secrets-store
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: archiverse-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: archiverse
  namespace: archiverse
spec:
  selector:
    app: archiverse
  ports:
  - port: 80
    targetPort: 3000
  type: ClusterIP
