apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: letsencrypt
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infrastructure/k8s/platform/security/letsencrypt
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  timeout: 5m0s
  dependsOn:
    - name: cert-manager
