apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: archiverse
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: frontend-sa
      nodeSelector:
        agentpool: frontendpool
      containers:
      - name: app-pool
        image: archiverseacr.azurecr.io/frontend # Base image, tag will be set by environment overlays
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        env:
        - name: NODE_ENV
          value: production
        - name: APP_BASE_URL
          valueFrom:
            secretKeyRef:
              name: archiverse-secrets
              key: app_base_url
        - name: NEXT_PUBLIC_AUTH0_DOMAIN
          valueFrom:
            secretKeyRef:
              name: archiverse-secrets
              key: next_public_auth0_domain
        - name: AUTH0_MANAGEMENT_API_DOMAIN
          valueFrom:
            secretKeyRef:
              name: archiverse-secrets
              key: auth0_management_api_domain
        - name: SESSION_ENCRYPTION_SECRET
          valueFrom:
            secretKeyRef:
              name: archiverse-secrets
              key: session_encryption_secret
        - name: AUTH0_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: archiverse-secrets
              key: auth0_client_id
        - name: AUTH0_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: archiverse-secrets
              key: auth0_client_secret
        - name: AUTH0_MANAGEMENT_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: archiverse-secrets
              key: auth0_management_client_id
        - name: AUTH0_MANAGEMENT_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: archiverse-secrets
              key: auth0_management_client_secret
        - name: AUTH0_ADMIN_ROLE_ID
          valueFrom:
            secretKeyRef:
              name: archiverse-secrets
              key: auth0_admin_role_id
        - name: AUTH0_MEMBER_ROLE_ID
          valueFrom:
            secretKeyRef:
              name: archiverse-secrets
              key: auth0_member_role_id
        - name: DEFAULT_CONNECTION_ID
          valueFrom:
            secretKeyRef:
              name: archiverse-secrets
              key: default_connection_id
        - name: CUSTOM_CLAIMS_NAMESPACE
          valueFrom:
            secretKeyRef:
              name: archiverse-secrets
              key: custom_claims_namespace
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 5
        startupProbe:
          httpGet:
            path: /
            port: 3000
          failureThreshold: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: archiverse
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 3000
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: frontend-network-policy
  namespace: archiverse
spec:
  podSelector:
    matchLabels:
      app: frontend
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector: {}
    ports:
    - protocol: TCP
      port: 3000
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: api
    ports:
    - protocol: TCP
      port: 80
  - to:
    - namespaceSelector: {}
      podSelector:
        matchLabels:
          k8s-app: kube-dns
    ports:
    - protocol: UDP
      port: 53
