apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: archiverse-frontend-secrets
  namespace: archiverse
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: ""
    keyvaultName: "archiverse-kv"
    cloudName: "AzurePublicCloud"
    tenantId: "24f581d7-7de0-4de5-b81a-27051d6e1be0"
    objects: |
      array:
        - |
          objectName: app-base-url
          objectType: secret
          objectAlias: APP_BASE_URL
        - |
          objectName: next-public-auth0-domain
          objectType: secret
          objectAlias: NEXT_PUBLIC_AUTH0_DOMAIN
        - |
          objectName: auth0-management-api-domain
          objectType: secret
          objectAlias: AUTH0_MANAGEMENT_API_DOMAIN
        - |
          objectName: auth0-client-id
          objectType: secret
          objectAlias: AUTH0_CLIENT_ID
        - |
          objectName: auth0-management-client-id
          objectType: secret
          objectAlias: AUTH0_MANAGEMENT_CLIENT_ID
        - |
          objectName: auth0-admin-role-id
          objectType: secret
          objectAlias: AUTH0_ADMIN_ROLE_ID
        - |
          objectName: auth0-member-role-id
          objectType: secret
          objectAlias: AUTH0_MEMBER_ROLE_ID
        - |
          objectName: default-connection-id
          objectType: secret
          objectAlias: DEFAULT_CONNECTION_ID
        - |
          objectName: custom-claims-namespace
          objectType: secret
          objectAlias: CUSTOM_CLAIMS_NAMESPACE
        - |
          objectName: session-encryption-secret
          objectType: secret
          objectAlias: SESSION_ENCRYPTION_SECRET
        - |
          objectName: auth0-client-secret
          objectType: secret
          objectAlias: AUTH0_CLIENT_SECRET
        - |
          objectName: auth0-management-client-secret
          objectType: secret
          objectAlias: AUTH0_MANAGEMENT_CLIENT_SECRET
  secretObjects:
    - data:
        # Environment variables
        - key: APP_BASE_URL
          objectName: APP_BASE_URL
        - key: NEXT_PUBLIC_AUTH0_DOMAIN
          objectName: NEXT_PUBLIC_AUTH0_DOMAIN
        - key: AUTH0_MANAGEMENT_API_DOMAIN
          objectName: AUTH0_MANAGEMENT_API_DOMAIN
        - key: AUTH0_CLIENT_ID
          objectName: AUTH0_CLIENT_ID
        - key: AUTH0_MANAGEMENT_CLIENT_ID
          objectName: AUTH0_MANAGEMENT_CLIENT_ID
        - key: AUTH0_ADMIN_ROLE_ID
          objectName: AUTH0_ADMIN_ROLE_ID
        - key: AUTH0_MEMBER_ROLE_ID
          objectName: AUTH0_MEMBER_ROLE_ID
        - key: DEFAULT_CONNECTION_ID
          objectName: DEFAULT_CONNECTION_ID
        - key: CUSTOM_CLAIMS_NAMESPACE
          objectName: CUSTOM_CLAIMS_NAMESPACE
      secretName: archiverse-env
      type: Opaque
    - data:
        # Sensitive secrets
        - key: SESSION_ENCRYPTION_SECRET
          objectName: SESSION_ENCRYPTION_SECRET
        - key: AUTH0_CLIENT_SECRET
          objectName: AUTH0_CLIENT_SECRET
        - key: AUTH0_MANAGEMENT_CLIENT_SECRET
          objectName: AUTH0_MANAGEMENT_CLIENT_SECRET
      secretName: archiverse-kv-secrets
      type: Opaque
