apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-sa
  namespace: archiverse
  annotations:
    azure.workload.identity/client-id: "e0323795-74ae-47a2-9e81-d9349c1a17d1"
    azure.workload.identity/tenant-id: "24f581d7-7de0-4de5-b81a-27051d6e1be0"
    azure.workload.identity/service-account-token-expiration: "86400"
  labels:
    azure.workload.identity/use: "true"
