apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-sa
  namespace: archiverse
  labels:
    azure.workload.identity/use: "true"
---
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentity
metadata:
  name: frontend-identity
  namespace: archiverse
spec:
  type: 0  # User-assigned managed identity
  resourceID: /subscriptions/68ba6806-178c-41f1-84ec-d7a839799be1/resourcegroups/MC_Archiverse_archiverse_westeurope/providers/Microsoft.ManagedIdentity/userAssignedIdentities/archiverse-agentpool
  clientID: 4b3ddf68-561e-451f-a92b-aded94cea508
---
apiVersion: aadpodidentity.k8s.io/v1
kind: AzureIdentityBinding
metadata:
  name: frontend-identity-binding
  namespace: archiverse
spec:
  azureIdentity: frontend-identity
  selector: frontend-identity
