apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
# Node pools are managed directly through Azure CLI
# - node-pools

patches:
- path: patches/frontend-image.yaml
