apiVersion: containerservice.azure.com/v1api20240801
kind: ManagedCluster
metadata:
  name: archiverse
  namespace: azureserviceoperator-system
spec:
  location: westeurope
  kubernetesVersion: "1.30"
  dnsPrefix: "archiverse-Archiverse-68ba68"
  nodeResourceGroup: "MC_Archiverse_archiverse_westeurope"
  sku:
    name: Base
    tier: Free
  identity:
    type: SystemAssigned
  networkProfile:
    networkPlugin: azure
    networkPolicy: none
    networkDataplane: azure
    loadBalancerSku: standard
    serviceCidr: "10.0.0.0/16"
    dnsServiceIP: "10.0.0.10"
    outboundType: loadBalancer
    ipFamilies:
      - IPv4
  addonProfiles:
    azureKeyvaultSecretsProvider:
      enabled: true
      config:
        enableSecretRotation: "false"
        rotationPollInterval: "2m"
    extensionManager:
      enabled: true
  securityProfile:
    workloadIdentity:
      enabled: true
  storageProfile:
    diskCSIDriver:
      enabled: true
    fileCSIDriver:
      enabled: true
    snapshotController:
      enabled: true
  oidcIssuerProfile:
    enabled: true
  autoScalerProfile:
    balanceSimilarNodeGroups: "false"
    expander: random
    maxEmptyBulkDelete: "10"
    maxGracefulTerminationSec: "600"
    maxNodeProvisionTime: "15m"
    maxTotalUnreadyPercentage: "45"
    newPodScaleUpDelay: "0s"
    okTotalUnreadyCount: "3"
    scaleDownDelayAfterAdd: "10m"
    scaleDownDelayAfterDelete: "10s"
    scaleDownDelayAfterFailure: "3m"
    scaleDownUnneededTime: "10m"
    scaleDownUnreadyTime: "20m"
    scaleDownUtilizationThreshold: "0.5"
    scanInterval: "10s"
    skipNodesWithLocalStorage: "false"
    skipNodesWithSystemPods: "true"
