apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: janusgraph
  namespace: archiverse
spec:
  serviceName: janusgraph
  replicas: 3
  selector:
    matchLabels:
      app: janusgraph
  template:
    metadata:
      labels:
        app: janusgraph
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: agentpool
                operator: In
                values:
                - storagepool
      containers:
      - name: janusgraph
        image: janusgraph/janusgraph:latest
        ports:
        - containerPort: 8182
          name: gremlin
        resources:
          requests:
            cpu: "2"
            memory: "4Gi"
          limits:
            cpu: "4"
            memory: "8Gi"
        env:
        - name: CASSANDRA_USER_FILE
          value: /mnt/secrets-store/cassandra-username
        - name: CASSANDRA_PASSWORD_FILE
          value: /mnt/secrets-store/cassandra-password
        volumeMounts:
        - name: janusgraph-config
          mountPath: /etc/opt/janusgraph
        - name: janusgraph-data
          mountPath: /var/lib/janusgraph
        - name: secrets-store
          mountPath: /mnt/secrets-store
          readOnly: true
        readinessProbe:
          tcpSocket:
            port: 8182
          initialDelaySeconds: 60
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8182
          initialDelaySeconds: 120
          periodSeconds: 20
      securityContext:
        fsGroup: 1000
        runAsUser: 1000
        runAsGroup: 1000
      volumes:
      - name: janusgraph-config
        configMap:
          name: janusgraph-config
          defaultMode: 0777
      - name: secrets-store
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: archiverse-secrets
  volumeClaimTemplates:
  - metadata:
      name: janusgraph-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: managed-csi
      resources:
        requests:
          storage: 50Gi
