apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cassandra
  namespace: archiverse
spec:
  serviceName: cassandra
  replicas: 3
  selector:
    matchLabels:
      app: cassandra
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: agentpool
                operator: In
                values:
                - storagepool
      terminationGracePeriodSeconds: 1800
      initContainers:
      - name: init-config
        image: busybox
        command: ['sh', '-c', 'cp /config-template/* /config/ && chown -R 999:999 /config/ && chmod -R 755 /config/']
        volumeMounts:
        - name: cassandra-config-template
          mountPath: /config-template
        - name: cassandra-config
          mountPath: /config
      containers:
      - name: cassandra
        image: cassandra:4.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 7000
          name: intra-node
        - containerPort: 7001
          name: tls-intra-node
        - containerPort: 7199
          name: jmx
        - containerPort: 9042
          name: cql
        resources:
          requests:
            cpu: "2"
            memory: "8Gi"
          limits:
            cpu: "4"
            memory: "16Gi"
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
        lifecycle:
          preStop:
            exec:
              command: 
              - /bin/sh
              - -c
              - nodetool drain
        env:
          - name: MAX_HEAP_SIZE
            value: "8G"
          - name: HEAP_NEWSIZE
            value: "2G"
          - name: CASSANDRA_SEEDS
            value: "cassandra-0.cassandra.archiverse.svc.cluster.local"
          - name: CASSANDRA_CLUSTER_NAME
            value: "arch-graph-cluster"
          - name: CASSANDRA_DC
            value: "dc1"
          - name: CASSANDRA_RACK
            value: "rack1"
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: CASSANDRA_CONF
            value: /opt/cassandra/conf
          - name: CASSANDRA_USER_FILE
            value: /mnt/secrets-store/cassandra-username
          - name: CASSANDRA_PASSWORD_FILE
            value: /mnt/secrets-store/cassandra-password
        volumeMounts:
        - name: cassandra-data
          mountPath: /var/lib/cassandra
        - name: cassandra-config
          mountPath: /etc/cassandra/cassandra.yaml
          subPath: cassandra.yaml
        - name: secrets-store
          mountPath: /mnt/secrets-store
          readOnly: true
      securityContext:
        fsGroup: 999
        runAsUser: 999
        runAsGroup: 999
      volumes:
        - name: cassandra-config
          configMap:
            name: cassandra-config
        - name: secrets-store
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: archiverse-secrets
  volumeClaimTemplates:
  - metadata:
      name: cassandra-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: managed-csi
      resources:
        requests:
          storage: 100Gi
