apiVersion: containerservice.azure.com/v1beta1
kind: AgentPool
metadata:
  name: backendpool
  namespace: azure-service-operator-system
spec:
  owner:
    name: archiverse
    namespace: azure-service-operator-system
  resourceGroup: archiverse
  agentPoolMode: User
  count: 2
  vmSize: Standard_B2ps_v2
  orchestratorVersion: "1.30.7"
  osDiskSizeGB: 64
  osType: Linux
  maxPods: 110
  availabilityZones:
    - "2"
  enableAutoScaling: true
  minCount: 2
  maxCount: 5
  nodeLabels:
    nodepool: backend-pool
  nodeTaints:
    - key: workload
      value: appservice
      effect: NoSchedule
