apiVersion: containerservice.azure.com/v1
kind: AgentPool
metadata:
  name: systempool
  namespace: archiverse
spec:
  type: VirtualMachineScaleSets
  mode: System
  count: 1
  vmSize: Standard_B2ps_v2
  orchestratorVersion: "1.30.7"
  osDiskSizeGB: 64
  osType: Linux
  maxPods: 110
  availabilityZones: ["1"]
  enableAutoScaling: false
  nodeLabels:
    nodepool: system-pool
  nodeTaints: []
---
apiVersion: containerservice.azure.com/v1
kind: AgentPool
metadata:
  name: frontendpool
  namespace: archiverse
spec:
  type: VirtualMachineScaleSets
  mode: User
  count: 2
  vmSize: Standard_B2ps_v2
  orchestratorVersion: "1.30.7"
  osDiskSizeGB: 64
  osType: Linux
  maxPods: 110
  availabilityZones: ["1", "2"]
  enableAutoScaling: true
  minCount: 2
  maxCount: 5
  nodeLabels:
    nodepool: frontend-pool
  nodeTaints:
    - key: workload
      value: frontend
      effect: NoSchedule
---
apiVersion: containerservice.azure.com/v1
kind: AgentPool
metadata:
  name: backendpool
  namespace: archiverse
spec:
  type: VirtualMachineScaleSets
  mode: User
  count: 2
  vmSize: Standard_B2ps_v2
  orchestratorVersion: "1.30.7"
  osDiskSizeGB: 64
  osType: Linux
  maxPods: 110
  availabilityZones: ["1", "2"]
  enableAutoScaling: true
  minCount: 2
  maxCount: 5
  nodeLabels:
    nodepool: backend-pool
  nodeTaints:
    - key: workload
      value: appservice
      effect: NoSchedule
---
apiVersion: containerservice.azure.com/v1
kind: AgentPool
metadata:
  name: dbpool
  namespace: archiverse
spec:
  type: VirtualMachineScaleSets
  mode: User
  count: 1
  vmSize: Standard_B2ps_v2
  orchestratorVersion: "1.30.7"
  osDiskSizeGB: 64
  osType: Linux
  maxPods: 110
  availabilityZones: ["1"]
  enableAutoScaling: false
  nodeLabels:
    nodepool: db-pool
  nodeTaints:
    - key: workload
      value: postgres
      effect: NoSchedule
