apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-user-msi
  namespace: default
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"          # Using managed identity
    userAssignedIdentityID: "53df0398-1058-494e-aeef-e3280509a5f0"   # Using same identity as flux-system
    keyvaultName: "archiverse-kv"         # Using same keyvault as flux-system
    objects: |
      array:
        - |
          objectName: ExampleSecret
          objectType: secret              
          objectVersion: ""               # Latest version
    tenantId: "24f581d7-7de0-4de5-b81a-27051d6e1be0"  # Using same tenant as flux-system
  secretObjects:
    - secretName: example-k8s-secret
      type: Opaque
      data:
        - objectName: ExampleSecret
          key: example-key
