apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
stringData:
  # Database credentials - populated by external secret store
  POSTGRES_HOST: ""
  POSTGRES_DB: ""
  POSTGRES_USER: ""
  POSTGRES_PASSWORD: ""

---
apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
type: Opaque
stringData:
  # Auth0 configuration - populated by external secret store
  AUTH0_CLIENT_ID: ""
  AUTH0_CLIENT_SECRET: ""
  AUTH0_MANAGEMENT_CLIENT_ID: ""
  AUTH0_MANAGEMENT_CLIENT_SECRET: ""
  AUTH0_ADMIN_ROLE_ID: ""
  AUTH0_MEMBER_ROLE_ID: ""
  DEFAULT_CONNECTION_ID: ""
  SESSION_ENCRYPTION_SECRET: ""
  APP_BASE_URL: ""

---
# External Secrets Operator configuration
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: azure-secret-store
spec:
  provider:
    azurekv:
      tenantId: ${AZURE_TENANT_ID}
      vaultUrl: ${AZURE_VAULT_URL}
      authSecretRef:
        clientId:
          name: azure-secret-creds
          key: client-id
        clientSecret:
          name: azure-secret-creds
          key: client-secret

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-secrets-sync
spec:
  secretStoreRef:
    name: azure-secret-store
    kind: SecretStore
  target:
    name: app-secrets
  data:
    - secretKey: POSTGRES_HOST
      remoteRef:
        key: postgres-host
    - secretKey: POSTGRES_DB
      remoteRef:
        key: postgres-db
    - secretKey: POSTGRES_USER
      remoteRef:
        key: postgres-user
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: postgres-password

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: auth-secrets-sync
spec:
  secretStoreRef:
    name: azure-secret-store
    kind: SecretStore
  target:
    name: auth-secrets
  data:
    - secretKey: AUTH0_CLIENT_ID
      remoteRef:
        key: auth0-client-id
    - secretKey: AUTH0_CLIENT_SECRET
      remoteRef:
        key: auth0-client-secret
    - secretKey: AUTH0_MANAGEMENT_CLIENT_ID
      remoteRef:
        key: auth0-management-client-id
    - secretKey: AUTH0_MANAGEMENT_CLIENT_SECRET
      remoteRef:
        key: auth0-management-client-secret
    - secretKey: AUTH0_ADMIN_ROLE_ID
      remoteRef:
        key: auth0-admin-role-id
    - secretKey: AUTH0_MEMBER_ROLE_ID
      remoteRef:
        key: auth0-member-role-id
    - secretKey: DEFAULT_CONNECTION_ID
      remoteRef:
        key: default-connection-id
    - secretKey: SESSION_ENCRYPTION_SECRET
      remoteRef:
        key: session-encryption-secret
    - secretKey: APP_BASE_URL
      remoteRef:
        key: app-base-url
