apiVersion: v1
kind: Secret
metadata:
  name: archiverse-env
  namespace: archiverse
type: Opaque
stringData:
  APP_BASE_URL: ""  # Will be set per environment
  NEXT_PUBLIC_AUTH0_DOMAIN: "studioq.eu.auth0.com"
  AUTH0_MANAGEMENT_API_DOMAIN: "studioq.eu.auth0.com"
  AUTH0_CLIENT_ID: "GTknbkr0Eog7U5rFiT3BJsSd10CoZzDD"
  AUTH0_MANAGEMENT_CLIENT_ID: "58opaHRGwiqhiiHR42saSqa28jxj88OC"
  AUTH0_ADMIN_ROLE_ID: "rol_gREOAu3NzefJNzmN"
  AUTH0_MEMBER_ROLE_ID: "rol_k4xN1luOGX8608PG"
  DEFAULT_CONNECTION_ID: "con_PYPDPRGXmpNF7F3w"
  CUSTOM_CLAIMS_NAMESPACE: "https://archiverse.studioq.biz"
