apiVersion: containerservice.azure.com/v1
kind: AgentPool
metadata:
  name: dbpool
  namespace: archiverse
spec:
  type: VirtualMachineScaleSets
  mode: User
  count: 1
  vmSize: Standard_B2ps_v2
  orchestratorVersion: "1.30.7"
  osDiskSizeGB: 64
  osType: Linux
  maxPods: 110
  availabilityZones: ["2"]
  enableAutoScaling: false
  nodeLabels:
    nodepool: db-pool
  nodeTaints:
    - key: workload
      value: postgres
      effect: NoSchedule
