apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - secrets.yaml
  - ingress.yaml
  - cert-manager.yaml

commonLabels:
  app.kubernetes.io/managed-by: flux
  app.kubernetes.io/part-of: archiverse
