apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: frontend
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: frontend
  policy:
    semver:
      range: '>=0.0.0'  # Accept all versions since we're using Run.ID as tags
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: frontend
  namespace: flux-system
spec:
  image: archiverseacr.azurecr.io/frontend
  interval: 1m0s  # Check for new images every minute
  secretRef:
    name: acr-auth  # Reference to ACR credentials secret
