apiVersion: containerservice.azure.com/v1
kind: ManagedClustersAgentPool
metadata:
  name: backendpool
  namespace: azureserviceoperator-system
spec:
  owner:
    name: archiverse
  mode: User
  count: 1
  vmSize: Standard_D2pls_v6
  maxPods: 30
  osDiskSizeGB: 128
  osType: Linux
  osDiskType: Managed
  kubeletDiskType: OS
  type: VirtualMachineScaleSets
  enableAutoScaling: true
  minCount: 1
  maxCount: 20
  scaleDownMode: Delete
  osSKU: Ubuntu
  upgradeSettings: {}
  enableFIPS: false
  securityProfile:
    enableVTPM: false
    enableSecureBoot: false
  nodeTaints:
    - "workload=backend:NoSchedule"
  nodeLabels:
    workload: backend
