apiVersion: containerservice.azure.com/v1api20240801
kind: ManagedClustersAgentPool
metadata:
  name: databasepool
  namespace: azureserviceoperator-system
spec:
  owner:
    name: archiverse
  mode: User
  count: 1
  vmSize: Standard_D2pls_v6
  maxPods: 30
  osDiskSizeGB: 512
  osType: Linux
  osDiskType: Managed
  kubeletDiskType: OS
  type: VirtualMachineScaleSets
  enableAutoScaling: false
  scaleDownMode: Delete
  osSKU: Ubuntu
  upgradeSettings: {}
  enableFIPS: false
  securityProfile:
    enableVTPM: false
    enableSecureBoot: false
  nodeTaints:
    - "workload=database:NoSchedule"
  nodeLabels:
    workload: database
    persistence: "true"
