apiVersion: containerservice.azure.com/v1api20210501
kind: ManagedClustersAgentPool
metadata:
  name: frontendpool
  namespace: azureserviceoperator-system
spec:
  owner:
    group: containerservice.azure.com
    kind: ManagedCluster
    name: archiverse
  mode: User
  count: 2
  vmSize: Standard_D2pls_v6
  availabilityZones:
    - "2"
  maxPods: 110
  osDiskSizeGB: 64
  osType: Linux
  nodeTaints:
    - "workload=frontend:NoSchedule"
  nodeLabels:
    workload: frontend
