apiVersion: containerservice.azure.com/v1api20210501
kind: ManagedCluster
metadata:
  name: archiverse
  namespace: azureserviceoperator-system
spec:
  location: westeurope
  nodeResourceGroup: archiverse
  kubernetesVersion: "1.27"
  dnsPrefix: "archiverse"
  agentPoolProfiles: []
  networkProfile:
    networkPlugin: azure
  owner:
    name: archiverse
