apiVersion: containerservice.azure.com/v1api20240801
kind: ManagedCluster
metadata:
  name: archiverse
  namespace: azureserviceoperator-system
spec:
  location: westeurope
  owner:
    name: archiverse
    group: resources.azure.com
    kind: ResourceGroup
  sku:
    name: Base
    tier: Free
  identity:
    type: SystemAssigned
  kubernetesVersion: "1.30"
  dnsPrefix: "archiverse-Archiverse-68ba68"
  nodeResourceGroup: "MC_Archiverse_archiverse_westeurope"
  enableRBAC: true
  networkProfile:
    networkPlugin: azure
    networkPolicy: none
    networkDataplane: azure
    loadBalancerSku: standard
    serviceCidr: "10.0.0.0/16"
    dnsServiceIP: "10.0.0.10"
    outboundType: loadBalancer
    ipFamilies:
      - IPv4
  addonProfiles:
    azureKeyvaultSecretsProvider:
      enabled: true
      config:
        enableSecretRotation: "false"
        rotationPollInterval: "2m"
    extensionManager:
      enabled: true
  securityProfile:
    workloadIdentity:
      enabled: true
  storageProfile:
    diskCSIDriver:
      enabled: true
    fileCSIDriver:
      enabled: true
    snapshotController:
      enabled: true
  oidcIssuerProfile:
    enabled: true
