apiVersion: resources.azure.com/v1api20200601
kind: ResourceGroup
metadata:
  name: archiverse
  namespace: azureserviceoperator-system
spec:
  location: westeurope
  operatorSpec:
    secretExpressions:
    - name: aso-controller-settings
      key: AZURE_SUBSCRIPTION_ID
