apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: azure-service-operator
  namespace: flux-system
spec:
  interval: 10m
  path: ./infrastructure/k8s/operators/azure-service-operator
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m
