apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: azure-service-operator
  namespace: azureserviceoperator-system
spec:
  interval: 5m
  chart:
    spec:
      chart: azure-service-operator
      version: "2.0.0"
      sourceRef:
        kind: HelmRepository
        name: azure-service-operator
        namespace: azureserviceoperator-system
      interval: 1m
  values:
    azureIdentity:
      enabled: true
      type: workload
    certManager:
      enabled: false
    webhook:
      certificate:
        generate: true
    crdPattern: "resources.azure.com/*;containerservice.azure.com/*;keyvault.azure.com/*;managedidentity.azure.com/*;eventhub.azure.com/*"
    image:
      repository: mcr.microsoft.com/k8s/azureserviceoperator
      tag: v2.0.0
      os: linux
      arch: amd64
    preUpgradeChecker:
      image:
        repository: mcr.microsoft.com/k8s/azureserviceoperator
        tag: v2.0.0
        os: linux
        arch: amd64
