apiVersion: v1
kind: Secret
metadata:
  name: aso-controller-settings
  namespace: azureserviceoperator-system
type: Opaque
stringData:
  USE_WORKLOAD_IDENTITY_AUTH: "true"
  AZURE_TENANT_ID: "24f581d7-7de0-4de5-b81a-27051d6e1be0"
  AZURE_SUBSCRIPTION_ID: "68ba6806-178c-41f1-84ec-d7a839799be1"
  AZURE_CLIENT_ID: "4b3ddf68-561e-451f-a92b-aded94cea508"
