apiVersion: v1
kind: Secret
metadata:
  name: aso-controller-settings
  namespace: azureserviceoperator-system
type: Opaque
stringData:
  USE_WORKLOAD_IDENTITY_AUTH: "true"
---
apiVersion: v1
kind: Secret
metadata:
  name: webhook-server-cert
  namespace: azureserviceoperator-system
type: Opaque
stringData:
  tls.crt: ""
  tls.key: ""
