apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-service
  namespace: archiverse
spec:
  selector:
    matchLabels:
      app: app-service
  template:
    metadata:
      labels:
        app: app-service
    spec:
      containers:
      - name: app-pool
        image: archiversedev.azurecr.io/app-service-dev # {"$imagepolicy": "flux-system:app-service-dev"}