version: v1.1.0

# Trigger on GitHub push events
trigger:
  sourceBranch: main
  sourceRepository: https://github.com/{{.Values.GITHUB_REPO}}
  sourceType: GitHub
  name: {{.Values.TASK_NAME}}

# Build settings
steps:
  # Build image using buildx for multi-platform support
  - build: >
      --platform linux/arm64
      -t {{.Run.Registry}}/archiverse:{{.Run.ID}} 
      -t {{.Run.Registry}}/archiverse:latest
      --build-arg BUILDPLATFORM=linux/amd64
      --build-arg TARGETPLATFORM=linux/arm64
      .
    workingDirectory: .

# Authentication and registry settings
auth:
  github:
    type: Pat
    identity: studioqsrl
    customToken: "{{.Values.GITHUB_TOKEN}}"

# Image tagging strategy
tags:
  - latest
  - {{.Run.ID}}

# Resource settings
platform:
  os: Linux
  architecture: amd64

# Build arguments and environment variables
env: []
