apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: archiverse

labels:
  - pairs:
      environment: production
    includeSelectors: false

configMapGenerator:
  - name: postgres-config
    namespace: archiverse
    files:
      - postgresql.conf

secretGenerator:
  - name: archiverse-secrets
    namespace: archiverse
    envs:
      - .env

images:
  - name: archiverseacr.azurecr.io/archiverse
    newTag: ec45db75f284630f856144624b5e69e1bfd9b27
  - name: archiverseacr.azurecr.io/app-service
    newTag: ec45db75f284630f856144624b5e69e1bfd9b27
  - name: postgres
    newTag: "15.4"

patches:
  - path: ingress-patch.yaml
    target:
      kind: Ingress
      name: archiverse

commonAnnotations:
  archiverse.io/environment: production
  archiverse.io/secrets-checksum: ${SECRETS_CHECKSUM}

replacements:
  - source:
      kind: Secret
      name: archiverse-secrets
      fieldPath: metadata.uid
    targets:
      - select:
          kind: Deployment
        fieldPaths:
          - spec.template.metadata.annotations.checksum/secrets
      - select:
          kind: StatefulSet
        fieldPaths:
          - spec.template.metadata.annotations.checksum/secrets
