apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: app-service-dev
  namespace: flux-system
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: development
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: 'update app-service-dev image to {{range .Updated.Images}}{{println .}}{{end}}'
    push:
      branch: development
  update:
    path: ./infrastructure/k8s/overlays/development
    strategy: Setters
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-service-dev
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./infrastructure/k8s/overlays/development
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: archiverse