---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: frontend
  namespace: flux-system
spec:
  image: archiverseacr.azurecr.io/frontend
  interval: 1m0s
  secretRef:
    name: acr-auth
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: frontend
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: frontend
  policy:
    semver:
      range: '>=0.0.0'
---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: frontend
  namespace: flux-system
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: development
    commit:
      author:
        email: fluxcdbot@users.noreply.github.com
        name: fluxcdbot
      messageTemplate: 'update frontend image to {{range .Updated.Images}}{{println .}}{{end}}'
    push:
      branch: development
  update:
    path: ./infrastructure/k8s/overlays/development
    strategy: Setters
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: frontend-dev
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./infrastructure/k8s/overlays/development
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: archiverse
