apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: archiverse

labels:
  - pairs:
      environment: production
    includeSelectors: false

images:
- name: archiverseacr.azurecr.io/archiverse
  newTag: latest

patches:
  - path: ingress-patch.yaml
    target:
      kind: Ingress
      name: archiverse

  - patch: |-
      apiVersion: v1
      kind: Secret
      metadata:
        name: archiverse-env
        namespace: archiverse
      stringData:
        APP_BASE_URL: "https://archiverse.studioq.biz"
        SESSION_ENCRYPTION_SECRET: "c1fc12f5ef9ed17847709676c22f26985fe75bc597369e8a7fcc3fa02ca0887f"
        AUTH0_CLIENT_SECRET: "J9aY-IulZAQDtjeWNNLuC4JNRNb7jI4Qzr7UKoPMkeI0Zwcd1rHyZCkOtKBTrGKE"
        AUTH0_MANAGEMENT_CLIENT_SECRET: "7kdLfE6WKWagJ901bmN2gnj5OlNR11SqcjC4YMUdGFNj3IYdsUflYiSTMTw_J6Rr"
    target:
      kind: Secret
      name: archiverse-env

  - patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/cpu
        value: 500m
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 512Mi
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/cpu
        value: 1000m
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 1Gi
      - op: replace
        path: /spec/template/spec/containers/0/env/0/value
        value: production
      - op: add
        path: /spec/template/spec/containers/0/readinessProbe
        value:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
      - op: add
        path: /spec/template/spec/containers/0/livenessProbe
        value:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 20
    target:
      kind: Deployment
      name: archiverse
