apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: archiverse
spec:
  template:
    spec:
      containers:
      - name: app-pool
        image: archiverseacr.azurecr.io/frontend:cb7d  # Using specific Run.ID tag for immutable reference
