apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: archiverse
spec:
  template:
    spec:
      containers:
      - name: app-pool
        image: archiverseacr.azurecr.io/frontend:v1.0.0  # Production uses explicit version tags, updated via PRs after testing in development
