apiVersion: v1
kind: ServiceAccount
metadata:
  name: postgres-sa
  namespace: archiverse
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: postgres-role
  namespace: archiverse
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: postgres-role-binding
  namespace: archiverse
subjects:
  - kind: ServiceAccount
    name: postgres-sa
    namespace: archiverse
roleRef:
  kind: Role
  name: postgres-role
  apiGroup: rbac.authorization.k8s.io
