apiVersion: v1
kind: ConfigMap
metadata:
  name: cassandra-config
data:
  cassandra.yaml: |
    cluster_name: 'arch-graph-cluster'
    num_tokens: 256
    authenticator: PasswordAuthenticator
    authorizer: CassandraAuthorizer
    role_manager: CassandraRoleManager
    seed_provider:
      - class_name: org.apache.cassandra.locator.SimpleSeedProvider
        parameters:
          - seeds: "cassandra-0.cassandra.default.svc.cluster.local"
    listen_address: ${POD_IP}
    broadcast_address: ${POD_IP}
    start_native_transport: true
    native_transport_port: 9042
    endpoint_snitch: GossipingPropertyFileSnitch
    auto_bootstrap: true
    concurrent_reads: 32
    concurrent_writes: 32
    concurrent_counter_writes: 32
    commitlog_sync: periodic
    commitlog_sync_period_in_ms: 10000
    commitlog_segment_size_in_mb: 32
    compaction_throughput_mb_per_sec: 16
    read_request_timeout_in_ms: 5000
    write_request_timeout_in_ms: 2000
    counter_write_request_timeout_in_ms: 5000
    cas_contention_timeout_in_ms: 1000
    truncate_request_timeout_in_ms: 60000
    request_timeout_in_ms: 10000
